### ISSUE TITLE
unable to recognize the utterance

### ISSUE THREAD

**Issue by raina99** [jjuraska/cruzhacks2018#3]
I cloned ur repo in my local and tried to run with following commands.

python3.6 client.py api -key de-DE simple dictation test2min.wav

Processing...

Sorry, we were unable to recognize the utterance.

please suggest how to make it run and whats the error

tried data/npr.wav as the files but still got the same output

**Comment by d3221** [comment]
+1 same problem:

Error: unexpected response type (Path header).
>> Sorry, we were unable to recognize the utterance.

`python3 client.py KEY en-US detailed dictation data/npr.wav`

**Comment by d3221** [comment]
Found a solution:
Your WAV file has to be recorded in special specifications. I tried: 
16 Bit
16 kHz
Mono Audio Channel

I converted the file with help of this website:
https://audio.online-convert.com/convert-to-wav

Hope this helps! :)

**Comment by raina99** [comment]
I am getting handshake error time and tme again. can you tell how much long file can you transcribe , does it convert a 10 min audio file at a time without needing to be divided into chunks.


thanks  for posting the solution , really appreciate it

**Comment by d3221** [comment]
I'm not the creator and I just tested it with a very short 10 second soundfile... 
I decided to do an external, dirty solution for my problem, because I need a realtime stream microphone input. 

Hope you get the help you need!

**Comment by raina99** [comment]
Appreciate your feedback and workaround on the issue you found. I only have a simple request to  make .
can you just verify how much long audio wav file it is able to transcribe ( i mean just to know how much minutes long file it can process, it must able to process at least 9 min file).
It would help me a lot.


If you just verify this for me , I would be highly obliged  because I am still struggling to test it myself .
Thanks for the feedback.

**Comment by d3221** [comment]
I don't have the repo on my pc anymore. You could send the sample file "npr.wav" to the server. What I saw, when I tested it, that only few seconds get recognized. The rest was simply thrown away. Just analyse it and listen to the sound file. On that point the return-phrase ends - this should be the time limit that is possible with that pice of code here.

Hope you understand what I mean :)

**Comment by raina99** [comment]
thanks man for your words.I tried it and it seems it does not exceed 52 sec for file and it not fixed like 15 sec just like REST API but varies as per the audio file.
